default: production
environments:
  local: "http://localhost:4000/fashionhub/"
  staging: "https://staging-env/fashionhub/"
  production: "https://pocketaces2.github.io/fashionhub/"
login:
  username: "demouser"
  password: "fashion123"
